config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root 'contacts#index'
  get '/contacts/page/:page', to: 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :taggings, dependent: :destroy 
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by_name!(name).contacts
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :contacts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:show, :edit, :update, :destroy]

  def index
    if (params.has_key?(:limit) && params.has_key?(:page))
      @limit = params[:limit].to_i
      @page = params[:page].to_i
    else
      @limit = 10
      @page = 1
    end
    @next_page = @page + 1
    @prev_page = @page - 1
    @contacts = Contact.all.order("created_at ASC")
                           .limit(@limit)
                           .offset(@limit * (@page - 1))
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    p contact_params
    if @contact.update(contact_params)
      redirect_to contact_path(@contact)
    else
      render 'edit'
    end
  end

  def destroy
    @contact.destroy
    redirect_to root_path
  end

  private

    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :tag_list)
    end

    def find_contact
      @contact = Contact.find(params[:id])
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
  end

  private

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
  <%= f.input :first_name, label: "First name" %>
  <%= f.input :last_name, label: "Last name" %>
  <%= f.input :tag_list, label: "Tags (separated by commas)" %>
  <%= link_to "Back", root_path, :class => "btn btn-primary" %> <%= f.button :submit %> 
<% end %>

app/views/contacts/edit.html.erb
<div class="container">

  <h1>Edit contact</h1>

  <%= render 'form' %>

</div>

app/views/contacts/index.html.erb
<div class="container">

    <h1>Contacts</h1>

      <div class="row vertical-align">
        <div class="col-md-10">
          <nav aria-label="Page_navigation">
            <ul class="pagination justify-content-end">
              <% if @page > 1 %>
                <li class="page-item">
                  <%= link_to "Previous", page: @prev_page, limit: @limit %>
                </li>
              <% else %>
                <li class="page-item disabled">
                  <a class="page-link">Previous</a>
                </li>
              <% end %>
              <li class="page-item disabled">
                <a class="page-link"> Page : <%= @page %></a>
              </li>
              <% if @contacts.length == @limit %>
                <li class="page-item">
                  <%= link_to "Next", page: @next_page, limit: @limit %>
                </li>
              <% else %>
                <li class="page-item disabled">
                  <a class="page-link">Next</a>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>

        <div class="col-md-2">
          <div class="btn-group justify-content-end">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Display by <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "10", {page: 1, limit: 10} %></li>
              <li><%= link_to "20", {page: 1, limit: 20} %></li>
              <li><%= link_to "50", {page: 1, limit: 50} %></li>
            </ul>
          </div>
        </div>
      </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>
            First name
          </th>
          <th>
            Last name
          </th>
          <th>
            Tags
          </th>
          <th>
            Update
          </th>
        </tr>
      <thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <th>
              <%= contact.first_name %>
            </th>
            <th>
              <%= contact.last_name %>
            </th>
            <th>
              <%= contact.tag_list %>
            </th>
            <th>
              <%= link_to "edit", contact, :class => "btn btn-warning" %>
            </th>
          </tr>
        <% end %>
      <tbody>
    </table>

    <div>
      <%= link_to "New contact", new_contact_path, :class => "btn btn-primary btn-block" %>
    </div>

</div>

app/views/contacts/new.html.erb
<div class="container">

  <h1>New contact</h1>

  <%= render 'form' %>

</div>

app/views/contacts/show.html.erb
<div class="container">

  <h1>Edit contact</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>
          First name
        </th>
        <th>
          Last name
        </th>
        <th>
          Tags
        </th>
      </tr>
    <thead>
    <tbody>
        <tr>
          <th>
            <%= @contact.first_name %>
          </th>
          <th>
            <%= @contact.last_name %>
          </th>
          <th>
            <%= @contact.tag_list %>
          </th>
        </tr>
    <tbody>
  </table>

  <%= link_to "Back", root_path, :class => "btn btn-primary" %>
  <%= link_to "Edit", edit_contact_path(@contact), :class => "btn btn-warning" %>
  <%= link_to "Delete", contact_path(@contact), method: :delete, data: { confirm: "Are you sure ?" }, :class => "btn btn-danger" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leikir</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>